name: Deploy to GitHub Pages

on:
  push:
    branches:
      - shop-v1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Updated to version 4

      - name: Set up Node.js
        uses: actions/setup-node@v4  # Updated to version 4
        with:
          node-version: 20  # Updated to Node.js 20

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4  # Updated to version 4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

      - name: Deploy Complete
        run: echo "Deployed to GitHub Pages!"
